# This file is automatically generated by pybind11-stubgen and generate_stubs.py
# Automatically generated files do not have a copyright

from __future__ import annotations
from vda5050_core._core import client
from vda5050_core._core import rmf_migration
from . import _core
__all__: list[str] = ['rmf_migration']
