[build-system]
requires = ["scikit-build-core>=0.11", "pybind11>=3.0"]
build-backend = "scikit_build_core.build"

[project]
name = "vda5050_core"
version = "0.0.0"
license = "Apache-2.0"
description = "Tools for VDA5050 development workflows"
#readme = "README.md"
authors = [
  { name = "Chen Bainian", email = "chen_bainian@a-star.edu.sg" },
]
requires-python = ">=3.10"
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
]


[dependency-groups]
test = ["pytest>=8.0"]
dev = [{ include-group = "test" }]


[tool.scikit-build]
minimum-version = "build-system.requires"
build.requires = ["catkin_pkg"]
build-dir = "build/{wheel_tag}"
wheel.install-dir = "vda5050_core"

[tool.scikit-build.wheel.packages]
vda5050_core = "python/vda5050_core"

[tool.uv]
cache-keys = [
  { file = "include/**/*.{h,c,hpp,cpp}" }, 
  { file = "src/**/*.{h,c,hpp,cpp}" }, 
  { file = "python/**/*.{h,c,hpp,cpp,txt}" }, 
  { file = "CMakeLists.txt" },
]

# [tool.pytest.ini_options]
# minversion = "8.0"
# addopts = ["-ra", "--showlocals", "--strict-markers", "--strict-config"]
# xfail_strict = true
# log_level = "INFO"
# filterwarnings = [
#   "error",
#   "ignore::pytest.PytestCacheWarning",
# ]
# testpaths = ["tests"]
# 
# 
# [tool.cibuildwheel]
# build-frontend = "build[uv]"
# test-command = "python -m pytest vda5050_core/python/tests"
# test-sources = ["vda5050_core/python/pyproject.toml", "vda5050_core/python/tests"]
# test-groups = ["test"]
